# Generated by Django 5.2.5 on 2025-08-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_name', models.CharField(max_length=100)),
                ('register_start_date', models.DateField(verbose_name='register start date')),
                ('register_end_date', models.DateField(verbose_name='register end date')),
                ('register_pages', models.IntegerField(default=0)),
                ('register_file', models.FileField(upload_to='register_pdfs')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='date of entry')),
                ('entry_author', models.CharField(max_length=100)),
                ('entry_title', models.CharField(max_length=100)),
                ('entry_volumes', models.CharField(max_length=100)),
                ('register_page', models.IntegerField(default=0)),
                ('register_line', models.IntegerField(default=0)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationers.register')),
            ],
        ),
    ]
