# Generated by Django 5.2.5 on 2025-08-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='register_line',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_edition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_volumes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
