[project]
name = "promprint-database"
version = "0.1.0"
description = "A django-based front end for editing and interacting with the promprint database."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
